"$schema" = 'https://starship.rs/config-schema.json'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[container]
format = '\[[$symbol \[$name\]]($style)\]'

[cpp]
format = '\[[$symbol($version(-$name))]($style)\]'

[direnv]
format = '\[[$symbol$loaded/$allowed]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_commit]
format = '\[[\($hash$tag\)]($style)\]'

[git_metrics]
format = '\[[+$added]($added_style)\]\[[-$deleted]($deleted_style)\]'

[git_state]
format = '\[[$state ($progress_current/$progress_total)]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'

[gradle]
format = '\[[$symbol($version)]($style)\]'

[hostname]
format = '\[[$ssh_symbol($hostname)]($style)\] '

[java]
format = '\[[$symbol($version)]($style)\]'

[jobs]
format = '\[[$symbol$number]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[maven]
format = '\[[$symbol($version)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[shell]
format = '\[[$indicator]($style)\]'

[status]
format = '\[[$symbol$status]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vcsh]
format = '\[vcsh [$symbol$repo]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
