"$schema" = 'https://starship.rs/config-schema.json'

[c]
format = '(via [$symbol($version(-$name) )]($style))'

[cpp]
format = '(via [$symbol($version(-$name) )]($style))'

[cmake]
format = '(via [$symbol($version )]($style))'

[dotnet]
format = '(via [$symbol($version )(🎯 $tfm )]($style))'

[golang]
format = '(via [$symbol($version )]($style))'

[java]
format = '(via [$symbol($version )]($style))'

[kotlin]
format = '(via [$symbol($version )]($style))'

[nodejs]
format = '(via [$symbol($version )]($style))'

[package]
format = '(is [$symbol$version]($style) )'

[python]
format = '(via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'

[rust]
format = '(via [$symbol($version )]($style))'

[zig]
format = '(via [$symbol($version )]($style))'
