"$schema" = 'https://starship.rs/config-schema.json'

[c]
format = "via [$symbol($name)]($style)"

[cmake]
format = "via [$symbol]($style)"

[cpp]
format = "via [$symbol($name)]($style)"

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[golang]
format = 'via [$symbol]($style)'

[gradle]
format = 'via [$symbol]($style)'

[java]
format = 'via [$symbol]($style)'

[kotlin]
format = 'via [$symbol]($style)'

[maven]
format = 'via [$symbol]($style)'

[meson]
format = 'via [$symbol]($style)'

[nodejs]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'

[zig]
format = 'via [$symbol]($style)'
