"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = "[.](bright-black) "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold purple)"
vimcmd_replace_one_symbol = "[<](bold purple)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[c]
symbol = "C "

[cpp]
symbol = "C++ "

[container]
symbol = "container "

[cmake]
symbol = "cmake "

[dotnet]
format = "via [$symbol($version )(target $tfm )]($style)"
symbol = ".NET "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[git_branch]
symbol = "git "
truncation_symbol = "..."

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[hostname]
ssh_symbol = "ssh "

[java]
symbol = "java "

[jobs]
symbol = "*"

[kotlin]
symbol = "kt "

[maven]
symbol = "maven "

[nodejs]
symbol = "nodejs "

[meson]
symbol = "meson "
truncation_symbol = "..."

[nix_shell]
symbol = "nix "

[package]
symbol = "pkg "

[python]
symbol = "py "

[rust]
symbol = "rs "

[shlvl]
symbol = "shlvl "

[status]
symbol = "[x](bold red) "
not_executable_symbol = "noexec"
not_found_symbol = "notfound"
sigint_symbol = "sigint"
signal_symbol = "sig"

[sudo]
symbol = "sudo "

[zig]
symbol = "zig "
