name: Build & Publish (Arch Linux)
on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build (release)
        run: cargo build --release --locked

      - name: Package artifact
        run: |
          mkdir -p artifacts
          tar -C target/release -czvf artifacts/starship-x86_64-unknown-linux-gnu.tar.gz starship

      - name: Create release and upload artifact
        uses: ncipollo/release-action@v1
        with:
          tag: build-${{ github.sha }}
          name: build-${{ github.sha }}
          artifacts: artifacts/starship-*.tar.gz
          repo: echohumm/starship
          token: ${{ secrets.GITHUB_TOKEN }}
          